import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :noshNetwork, NoshNetworkWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :noshNetwork,
  paystack_config: [
    secret_key: "sk_test_38bfad036e3e593234dc207fd109ff8461b70816",
    public_key: "pk_test_4df7a65972e448e5f9a211f5c626e0acfe341da0"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: NoshNetwork.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
